
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="ARR"

[[mods]] #mandatory

modId= "ohmygoat" #mandatory

version = "${version}"

displayName="Oh My Goat" #mandatory

logoFile="icon.png" #optional

credits="Mehvahdjukaar, Plantkillable" #optional

authors="MehVahdJukaar, Plantkillable" #optional

itemIcon="minecraft:goat_horn" #catalogue icon

description='''
Ram blocks for automation, Viking helmets and Geeps!
'''

[[dependencies.ohmygoat]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.ohmygoat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ohmygoat]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.1.20,]"
    side="BOTH"
